site_name: Logis SDK 文档
site_description: Logis SDK 官方文档
repo_url: https://github.com/xdewx/logis-sdk
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    # - navigation.expand # 展开导航
    - navigation.top # 顶部导航
    - navigation.footer # 页脚导航
    - navigation.indexes # 索引页支持
    - navigation.tracking # 跟随导航
    # - navigation.instant # 无刷新导航
    - search.suggest
    - search.highlight
    - toc.fold
    # - toc.integrate # 整合TOC
    - toc.follow # 跟随TOC
    - content.code.copy # 代码块复制按钮
    # - content.action.edit # 编辑按钮（配合 repo_url）
    - content.action.view # 查看源码按钮
    - content.tooltips # 提示框
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到浅色模式

plugins:
  - search
  - macros:
      module_name: macro
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.] # 关键：让工具找到你的 logis包
          options:
            show_root_toc_entry: false # 全局关闭根节点toc，避免重复
            show_source: true
            show_bases: false
            show_docstring_attributes: true
            docstring_style: google
            show_if_no_docstring: true # 显示无文档字符串的成员
            show_signature_annotations: true # 显示类型注解
            separate_signature: true # 签名单独显示

markdown_extensions:
  # 提示框扩展（必需）
  - admonition

  # 可选：增强提示框样式
  - pymdownx.details # 可折叠提示框
  - pymdownx.superfences # 代码块支持
  - pymdownx.inlinehilite # 行内代码高亮

  # 其他常用扩展
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets # 文件包含
  - attr_list # 属性列表
  - md_in_html # HTML 中嵌套 Markdown
  - tables # 表格
  - toc:
      permalink: true # 标题锚点

extra:
  module_name: logis
  toc:
    collapse: true # 全局折叠TOC
    depth: 2

nav:
  - 首页: index.md
  - 使用指南:
    - 快速开始:
      - 查看版本号: quickstart/version.md
    - 高级用法:
      - 自定义策略: advanced/strategy.md
  - 接口文档:
    - 通用模块:
      - 数据结构: type.md
      - 日志: logging.md
      - 任务: task.md
      - 指标: metric.md
    - 仿真大师模块:
      - 数据结构: sim/type.md
      - 搬运: sim/transport.md
      - 存储: sim/storage.md
      - 智能体: sim/agent.md

extra_javascript:
  - assets/hook.js
